### PR TITLE
Enhancement: Add support for PHP 8.4

### PR DESCRIPTION
**Pull request by Chris53897**
This pull request

- [x] adds support for PHP 8.4

### CODE REVIEW

**Comment by ruudk** [comment]
@localheinz Could you have a look at this? We need to solve https://github.com/ergebnis/composer-normalize/issues/1390

**Comment by jolelievre** [comment]
Maybe the CI should be updated to handle PHP until 8.4?

**Comment by ruudk** [comment]
> Maybe the CI should be updated to handle PHP up to 8.4?

That's exactly what this PR does.

**Comment by Chris53897** [comment]
This PR only includes Testruns for more PHP versions.

The Fix for PHP 8.4 deprecation is here.
https://github.com/localheinz/diff/pull/72

**Comment by ruudk** [comment]
Spoke with Andreas and it will be handled end of the week. 🥳

**Comment by xHeaven** [comment]
Is there any update on this?

**Comment by localheinz** [comment]
Thank you, @Chris53897, @Chris8934, @jolelievre, @ruudk, and @xHeaven!

**Pull request merged**
